### ISSUE TITLE
Nice repo

### ISSUE THREAD

**Issue by TinyYolo** [ZhejianglabNCRC/SPAIC#25]
This codebase appears to be solely Torch-based, so why does it wraps Torch's basic operations again? Is this really necessary? The framework presented in the codebase is somewhat complicated (compared with substitutes), but the running examples provided do not appear to exploit such design, quite odd. BTW, the implementations of the algorithms (inside the learning subfolder) have varied code styles. 
I haven't tried this repository yet, might try it later, but it doesn't look very appealing.

**Comment by hongchaofei** [comment]
Thanks for your attention. This framework is designed to support multiple backends. Currently, we are mainly working on the PyTorch-based backend, but other backends such as JAX-based backend and Neuromorphic hardware-based backend is also under development.

As you mentioned “the codebase is somewhat complicated”, could you please provide some more specific information? If you are referring to the modules like Connection, Projection and Assembly, that is because we aim to support algorithms with deeper integration of deep learning and neuroscience theories. We introduced more neuroscience coding-styles and functionalities to our framework, which may not be very straight forward from traditional deep learning viewpoint but provide more probability for neuromorphic algorithms. Some more examples can be found in [ZhejianglabNCRC/SPAIC_paper_examples (github.com)](https://github.com/ZhejianglabNCRC/SPAIC_paper_examples), which further show how to use Connections, Projections and so on.

For “algorithms have varied code styles”, that maybe due to inherent differences between different algorithms, such as gradient-based learning rules and synapse plasticity (local) learning rules. We are trying to provide a more consistent algorithm coding style, but given the diversity of SNN learning rules, it takes more time to build a widely applicable standard.
